apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vob1ie4c6-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:59296adaa3fc6f03d5964c47f0f96d6cc5e4197b@sha256:04ab7aaeb4938b6c1d7fda7149987b555ca6e71f8b0c3a785628cc559b95e96a
          name: container-image
